#ifndef CONFIGERROR_HPP
    #define CONFIGERROR_HPP

#include "webserv.hpp"

enum ConfigErrorType
{
    ERR_CFG_CANNOT_OPEN,
    ERR_CFG_MISSING_SERVER,
    ERR_CFG_MISSING_OPEN_BRACE,
    ERR_CFG_UNCLOSED_SERVER,
    ERR_CFG_UNCLOSED_LOCATION,
    ERR_CFG_MISSING_SEMICOLON,
    ERR_CFG_EMPTY_VALUE,
    ERR_CFG_INVALID_PORT,
    ERR_CFG_PORT_RANGE,
    ERR_CFG_INVALID_CODE,
    ERR_CFG_MISSING_ERROR_PAGE,
    ERR_CFG_EMPTY_METHODS,
    ERR_CFG_MISSING_PATH,
    ERR_CFG_MISSING_DIRECTIVE,
    ERR_CFG_DUPLICATE_DIRECTIVE,
    ERR_CFG_UNKNOWN_DIRECTIVE,
    ERR_CFG_INVALID_METHOD,
    ERR_CFG_CODE_RANGE,
    ERR_CFG_INVALID_PATH,
    ERR_CFG_INVALID_CGI_EXTENSION,
    ERR_CFG_MISSING_CGI_PATH,
};

void throwConfigError(ConfigErrorType type, std::string const& detail = "");

#endif
