server
{
    host        0.0.0.0;
    port        8080;
    root        www;
    index       index.html;
    error_page  404 www/404.html;

    location /
    {
        methods     GET POST DELETE;
        autoindex   off;
    }

    location /cgi-bin
    {
        methods         GET POST;
        cgi_extension   .py /opt/homebrew/bin/python3;
        cgi_extension   .sh /bin/bash;
    }
}

server
{
    host        0.0.0.0;
    port        8081;
    root        www;
    index       index.html;
    error_page  404 www/404.html;

    location /
    {
        methods     GET;
        autoindex   on;
    }
}
